### PR TITLE
"Invalid report" fix, hide pins button

### LINKED ISSUE #156: User bug report - invalid report
"When I try to add a report to fix my street app it keeps saying invalid report this information required ( it doesn't say what information this is). it also says my email/password combination is incorrect so I change d my password successfully and it still says invalid report this information required . This only happens on the app.

"I have checked and there are no updates so I am using the most up to date version .i am running iOS 7.0.2"

### LINKED ISSUE #175: Add 'Hide pins' option to app
A few app users have noted that fixed problems are clogging up the map view on the app, so they're finding it difficult to report new problems. They have asked if there is a way to hide the pins when they are making new reports. There currently isn't an option to 'Hide pins' on the iPhone app.

### LINKED ISSUE #263: Email address in help section should start an email
> in the help section on the app clicking on your email address does nothing when I expect the app to run an email app to create a new email

The links to webpages all start up the phone's browser app, but tapping on the email address does nothing.

### PR DESCRIPTION
**Pull request by davea**
A few little bug fixes and improvements:

- Button to hide pins on map. #175
- Skip empty report details screen.
- Correctly set user title. #156
- Show more helpful error if server rejects password. #156
- Allow mailto: links to be followed. #263
- Stop keyboard obscuring report details text field. #222

pin toggle

Fixes #175, fixes #156, fixes #263.

### CODE REVIEW

File: www/js/views/submit.js [hunk 1]
```diff
@@ -86,7 +86,7 @@
                 if ( !this._handleInvalid( model, err, options ) ) {
                     var errors = err.errors;
                     var errorList = '<ul><li class="plain">' + FMS.strings.invalid_report + '</li>';
-                    var validErrors = [ 'password', 'category', 'name' ];
+                    var validErrors = [ 'password', 'password_register', 'category', 'name' ];
```
Comment (dracos) [inline www/js/views/submit.js]: Sorry, wonder why I didn't use password – I guess it appears in a different part of the web interface.

File: www/js/views/around.js [hunk 2]
```diff
@@ -267,7 +268,6 @@
 
             onClickCancel: function(e) {
                 e.preventDefault();
-                fixmystreet.markers.removeAllFeatures();
```
Comment (dracos) [inline www/js/views/around.js]: Not sure what removing this line does, is it done again elsewhere?

Comment (davea) [reply www/js/views/around.js]: Yep, the markers are refreshed on line 273. The previous behaviour would cause all the markers to disappear for a couple of seconds when returning to the map screen, which I thought was a bit confusing with the addition of the hide pins button. I couldn't see a reason for the markers to be programmatically removed before being refreshed from the server, but happy to put it back if there was one!

Comment (dracos) [reply www/js/views/around.js]: I assume not – actually links with https://github.com/mysociety/fixmystreet/issues/2059 similar!
